name: windows-bundler

on:
  pull_request:

  push:
    branches:
      - master

jobs:
  windows_bundler:
    runs-on: windows-latest

    env:
      RGV: ..

    strategy:
      matrix:
        ruby: [ '2.7' ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: none
      - name: Install dependencies
        run: |
          bin/rake spec:parallel_deps
        shell: bash
        working-directory: ./bundler
      - uses: actions/checkout@v2
        with:
          repository: deivid-rodriguez/parallel_tests
          ref: fix_fetch_issue
          path: bundler/parallel_tests
      - name: Run specs
        run: |
          parallel_tests/bin/parallel_rspec spec
        shell: bash
        working-directory: ./bundler
